# -*- coding: utf-8 -*-
"""
/***************************************************************************
 YOLO-MOD
                                 A QGIS plugin
Deep learning-based object detection in raster data using Ultralytics YOLO models, including support for custom models and interactive editing within QGIS.
Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-26
        copyright            : (C) 2026 by Mateusz Strzelecki and Marcin Ciecholewski, Gdansk University of Technology, Poland
        email                : marcin.ciecholewski@pg.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load YOLOMod class from file YOLOMod.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .yolo_mod import YOLOMod
    return YOLOMod(iface)
