# -*- coding: utf-8 -*-
"""
/***************************************************************************
 YOLO-MOD
                               
 QGIS plugin: YOLO-based detection of aircraft, airports, ships, helicopters, and storage tanks in satellite imagery.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-04-26
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Mateusz Strzelecki, Miraslau Farelnik and Marcin Ciecholewski
        email                : marcin.ciecholewski@pg.edu.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import datetime
import numpy as np
from qgis.core import (
    QgsSettings,
    QgsCategorizedSymbolRenderer,
    QgsFeature,
    QgsField,
    QgsFillSymbol,
    QgsGeometry,
    QgsMapRendererCustomPainterJob,
    QgsMapSettings,
    QgsPointXY,
    QgsProject,
    QgsRendererCategory,
    QgsVectorFileWriter,
    QgsVectorLayer,
    QgsMapLayer,
    QgsRectangle
)
from qgis.PyQt.QtCore import QMetaType, QSize, Qt, QRect
from qgis.PyQt.QtGui import QColor, QIcon, QImage, QPainter, QPixmap, QPen
from qgis.PyQt.QtWidgets import QAction, QDialog, QVBoxLayout, QLabel, QDialogButtonBox
from ultralytics import YOLO
from onnxruntime import InferenceSession
import cv2

from .yolo_mod_dialog import YOLOModDialog


class PreviewPopup(QDialog):
    """A simple popup window to display an image with rendered bounding boxes."""
    def __init__(self, pixmap, parent=None):
        super().__init__(parent)
        self.setWindowTitle("YOLO Export Preview")
        layout = QVBoxLayout(self)
        label = QLabel()
        label.setPixmap(pixmap)
        label.setAlignment(Qt.AlignCenter)
        layout.addWidget(label)
        self.setLayout(layout)


class YOLOMod:
    """Main plugin class integrating YOLO detection into QGIS.

    This class manages the plugin lifecycle, GUI actions, model loading,
    object detection on a selected vector layer, and exporting results.
    """
    def __init__(self, iface):
        self.selectedLayer = None
        self.dlg = None
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.first_start = None
        self.actions = []
        self.menu = "&YOLO-MOD"
        self.model_cache = {}
        self.last_selected_layer_name = None
        self.object_names = {
            "airport": "airport",
            "helicopter": "helicopter",
            "plane": "aircraft",
            "oiltank": "storage tank",
            "warship": "warship",
            "ship": "civilian ship"
        }
        self.object_ids = {
            "plane": 0,
            "bridge": 1,
            "airport": 2,
            "harbor": 3,
            "vehicle": 4,
            "ship": 5
        }

    def _get_layer_by_name(self, name):
        """Helper to find a map layer by its name.

        Args:
            name (str): The name of the map layer to find.

        Returns:
            QgsMapLayer or None: The first matching map layer object, or None if not found.
        """
        layers = QgsProject.instance().mapLayersByName(name)
        return layers[0] if layers else None

    def _push_message(self, title, message, level=0, duration=2):
        """Helper to push messages to the QGIS message bar.

        Args:
            title (str): The title of the message.
            message (str): The body content of the message.
            level (int, optional): Message level (0: info, 1: warning, 2: critical). Defaults to 0.
            duration (int, optional): Duration to show the message in seconds. Defaults to 2.
        """
        self.iface.messageBar().pushMessage(title, message, level=level, duration=duration)

    def _get_filtered_layers(self, exclude_layer_name=None):
        """Helper to get map layers while excluding YOLO detection layers.

        Args:
            exclude_layer_name (str, optional): A specific layer name to exclude from the list. 
                Defaults to None.

        Returns:
            list[QgsMapLayer]: A list of map layers matching the filter criteria.
        """
        clean_layers = []
        for layer in self.iface.mapCanvas().mapSettings().layers():
            if exclude_layer_name and layer.name() == exclude_layer_name:
                continue
            if layer.name().startswith("YOLO Detections"):
                continue
            clean_layers.append(layer)
        return clean_layers

    def _render_to_image(self, settings, width, height, transparent=True):
        """Helper to render map settings to a QImage.

        Args:
            settings (QgsMapSettings): Map settings to use for rendering.
            width (int): Target image width in pixels.
            height (int): Target image height in pixels.
            transparent (bool, optional): Whether to use a transparent background. 
                Defaults to True.

        Returns:
            QImage: The rendered map image.
        """
        image = QImage(QSize(width, height), QImage.Format_ARGB32_Premultiplied)
        image.fill(QColor(0, 0, 0, 0) if transparent else QColor(0, 0, 0))
        painter = QPainter(image)
        job = QgsMapRendererCustomPainterJob(settings, painter)
        job.start()
        job.waitForFinished()
        painter.end()
        return image

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):
        """Adds an action to the QGIS UI (toolbar and/or menu).

        Args:
            icon_path (str): Path to the icon file.
            text (str): Display text for the action.
            callback (function): Function to call when the action is triggered.
            enabled_flag (bool, optional): Initial enabled state. Defaults to True.
            add_to_menu (bool, optional): Whether to add to the plugin menu. Defaults to True.
            add_to_toolbar (bool, optional): Whether to add to the toolbar. Defaults to True.
            status_tip (str, optional): Tooltip text for the status bar. Defaults to None.
            whats_this (str, optional): "What's this" help text. Defaults to None.
            parent (QWidget, optional): Parent widget for the action. Defaults to None.

        Returns:
            QAction: The created action object.
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip:
            action.setStatusTip(status_tip)
        if whats_this:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Initializes the plugin's graphical user interface components."""
        icon_path = f"{self.plugin_dir}/icon.png"
        self.add_action(
            icon_path,
            text="Run YOLO detection",
            callback=self.run,
            parent=self.iface.mainWindow(),
        )
        self.first_start = True

    def unload(self):
        """Removes plugin actions from QGIS UI when unloading the plugin."""
        for action in self.actions:
            self.iface.removePluginMenu(self.menu, action)
            self.iface.removeToolBarIcon(action)

    def get_model(self, model_path):
        """Loads and caches a YOLO or ONNX model from disk.

        Args:
            model_path (str): The absolute path to the .pt or .onnx model file.

        Returns:
            YOLO or InferenceSession or None: The loaded model object, or None if the path is invalid.
        """
        if model_path not in self.model_cache:
            if not os.path.exists(model_path):
                self._push_message("Error", f"Invalid model path: {model_path}", level=2, duration=4)
                return None

            if model_path.endswith(".pt"):
                self.model_cache[model_path] = YOLO(model_path)
            elif model_path.endswith(".onnx"):
                self.model_cache[model_path] = InferenceSession(model_path, providers=["CPUExecutionProvider"])
            else:
                self._push_message("Error", "Unsupported model format. Use .pt or .onnx", level=2, duration=4)
                return None

        return self.model_cache[model_path]

    def run(self):
        """Shows the plugin dialog and dispatches actions based on user input.

        Prepares layer lists, restores last-used settings, and either
        runs detection or performs export depending on the selected tab.
        """
        if self.first_start:
            self.first_start = False
            self.dlg = YOLOModDialog()

        # Update labels and selection info based on active layer
        active_layer = self.iface.activeLayer()
        if active_layer and active_layer.type() == QgsMapLayer.VectorLayer:
            selected_count = active_layer.selectedFeatureCount()
            if selected_count > 0:
                is_yolo = active_layer.name().startswith("YOLO Detections")
                info_text = f"Selected {selected_count} feature(s) from layer: {active_layer.name()}"
                self.dlg.set_selection_info(info_text, enabled=is_yolo)
            else:
                self.dlg.set_selection_info("No features selected in the active layer.", enabled=False)
        else:
            self.dlg.set_selection_info("No active vector layer selected in QGIS.", enabled=False)

        settings = QgsSettings()
        layers = QgsProject.instance().mapLayers().values()
        last_layer_name = settings.value("YOLOMod/last_layer", "")
        canvas_size = self.iface.mapCanvas().size()

        self.dlg.setup_ui_state(layers, last_layer_name, canvas_size)

        self.dlg.show()
        result = self.dlg.exec_()

        if result:
            self._dispatch_tab_action(result)

    def _dispatch_tab_action(self, result):
        """Dispatches the appropriate method based on the active tab and button clicked.

        Args:
            result (int): The dialog's return code.
        """
        current_tab = self.dlg.tabWidget.currentIndex()

        tab_actions = {
            0: self.handle_detection_tab,
            1: self.handle_edit_tab,
            2: self.handle_export,
            3: self.handle_preview,
            4: self.handle_tiling
        }

        handler = tab_actions.get(current_tab)
        if handler:
            if current_tab == 1:
                handler(result)
            else:
                handler()

    def handle_detection_tab(self):
        """Processes logic for the main detection tab."""
        selected_layer_name = self.dlg.comboBox.currentText()
        self.selectedLayer = self._get_layer_by_name(selected_layer_name)

        if not self.selectedLayer:
            return

        settings = QgsSettings()
        self.last_selected_layer_name = self.selectedLayer.name()
        settings.setValue("YOLOMod/last_layer", self.last_selected_layer_name)

        is_custom, model_path, colors = self.dlg.get_active_model_info()
        self.class_colors = colors
        self.conf_threshold = self.dlg.get_confidence_threshold()
        self.is_new_mode = (self.dlg.get_save_option() == "new")

        if is_custom:
            if not model_path:
                self._push_message("Error", "Please select a custom model path.", level=2, duration=4)
                return
            self.models_to_run = [model_path]
            model = self.get_model(model_path)
            if model and hasattr(model, 'names'):
                self.active_class_names = list(model.names.values())
        else:
            self.models_to_run = [self.dlg.lineEdit_model1.text()]
            self.active_class_names = ["airport", "helicopter", "aircraft", "storage tank", "warship", "civilian ship"]
            if self.dlg.get_run_multiple():
                second_model = self.dlg.get_second_model_path()
                if second_model == self.dlg.lineEdit_model1.text():
                    self._push_message("Error", "Models are the same.", level=2, duration=4)
                    return
                if second_model:
                    self.models_to_run.append(second_model)

        self.detect_objects()

    def handle_edit_tab(self, result):
        """Processes logic for the edit (merge/delete) tab.
        
        Args:
            result (int): The dialog's return code.
        """
        if result == 10:
            self.handle_merge()
        elif result == 11:
            self.handle_delete_selected()

    def handle_export(self):
        """Exports the current map canvas image and/or YOLO detection labels.

        Validates the export directory, optionally saves a PNG of the canvas,
        and writes YOLO-format label files (.txt) from a chosen detection layer.
        """
        export_dir = self.dlg.lineEdit_export_dir.text()
        if not export_dir or not os.path.isdir(export_dir):
            self._push_message("Error", "Invalid export directory.", level=2, duration=4)
            return

        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        base_filename = f"yolo_export_{timestamp}"

        canvas = self.iface.mapCanvas()
        extent = canvas.extent()

        # Save map canvas to PNG
        if self.dlg.checkBox_save_canvas.isChecked():
            img_path = os.path.join(export_dir, f"{base_filename}.png")
            settings = canvas.mapSettings()
            export_layer_name = self.dlg.comboBox_export_layer.currentText()
            settings.setLayers(self._get_filtered_layers(exclude_layer_name=export_layer_name))

            image = self._render_to_image(settings, settings.outputSize().width(), settings.outputSize().height())
            image.save(img_path)
            self._push_message("Export", f"Image saved: {base_filename}.png", level=0, duration=2)

        # If user requested saving YOLO labels, write a .txt file with normalized bboxes
        if self.dlg.checkBox_save_yolo.isChecked():
            selected_layer_name = self.dlg.comboBox_export_layer.currentText()
            target_layer = self._get_layer_by_name(selected_layer_name)

            if not target_layer:
                self._push_message("Error", "Selected export layer not found.", level=2, duration=4)
                return

            txt_path = os.path.join(export_dir, f"{base_filename}.txt")
            
            request = target_layer.getFeatures(extent)

            yolo_lines = []
            for feature in request:
                geom = feature.geometry()
                if not geom:
                    continue

                bbox = geom.boundingBox()
                if not extent.contains(bbox):
                    continue

                # Normalization logic
                norm_x_min = (bbox.xMinimum() - extent.xMinimum()) / extent.width()
                norm_x_max = (bbox.xMaximum() - extent.xMinimum()) / extent.width()
                norm_y_min = (extent.yMaximum() - bbox.yMaximum()) / extent.height()
                norm_y_max = (extent.yMaximum() - bbox.yMinimum()) / extent.height()
                x_center = (norm_x_min + norm_x_max) / 2.0
                y_center = (norm_y_min + norm_y_max) / 2.0
                w = abs(norm_x_max - norm_x_min)
                h = abs(norm_y_max - norm_y_min)

                class_name = feature["class"]
                if class_name in self.active_class_names:
                    class_id = self.active_class_names.index(class_name)
                else:
                    class_id = self.object_ids.get(class_name, 0)

                yolo_lines.append(f"{class_id} {x_center:.6f} {y_center:.6f} {w:.6f} {h:.6f}")

            with open(txt_path, "w") as f:
                f.write("\n".join(yolo_lines))

            self._push_message("Export", f"YOLO labels saved: {base_filename}.txt", level=0, duration=2)

    def handle_merge(self):
        """Copies all features from the source layer to the destination layer.

        Detects missing fields in the destination layer and adds them before
        transferring geometries and attributes. Copies symbology categories 
        from source to target if both use categorized renderers.
        """
        from_name, to_name = self.dlg.get_merge_layers()
        
        if from_name == to_name:
            self._push_message("Error", "Source and destination layers must be different.", level=2)
            return

        source_layer = self._get_layer_by_name(from_name)
        dest_layer = self._get_layer_by_name(to_name)

        if not source_layer or not dest_layer:
            return

        # Synchronize attribute fields
        src_fields = source_layer.fields()
        dst_fields = dest_layer.fields()
        missing_fields = [f for f in src_fields if dst_fields.indexFromName(f.name()) == -1]

        if missing_fields:
            dest_layer.dataProvider().addAttributes(missing_fields)
            dest_layer.updateFields()
            dst_fields = dest_layer.fields()

        # Build feature list for batch insertion
        new_features = []
        for feat in source_layer.getFeatures():
            new_feat = QgsFeature(dst_fields)
            new_feat.setGeometry(feat.geometry())
            
            for field in src_fields:
                attr_val = feat[field.name()]
                new_feat.setAttribute(field.name(), attr_val)
                
            new_features.append(new_feat)

        if new_features:
            dest_layer.startEditing()
            success = dest_layer.addFeatures(new_features)
            if success:
                dest_layer.commitChanges()
                # Update symbology categories
                src_renderer = source_layer.renderer()
                dst_renderer = dest_layer.renderer()

                if isinstance(src_renderer, QgsCategorizedSymbolRenderer) and isinstance(dst_renderer, QgsCategorizedSymbolRenderer):
                    existing_dst_values = [c.value() for c in dst_renderer.categories()]
                    changed = False

                    for src_cat in src_renderer.categories():
                        if src_cat.value() not in existing_dst_values:
                            new_cat = QgsRendererCategory(
                                src_cat.value(), 
                                src_cat.symbol().clone(), 
                                src_cat.label(),
                                src_cat.renderState()
                            )
                            dst_renderer.addCategory(new_cat)
                            changed = True

                    if changed:
                        dest_layer.triggerRepaint()
                        self.iface.layerTreeView().refreshLayerSymbology(dest_layer.id())

                self._push_message("Success", f"Merged {len(new_features)} features into {to_name}", level=0, duration=2)
            else:
                dest_layer.rollBack()
                self._push_message("Error", "Failed to add features to destination layer.", level=2, duration=4)

    def handle_delete_selected(self):
        """Deletes selected features from the currently active layer in QGIS.

        Restricted to layers starting with 'YOLO Detections' for safety.
        """
        layer = self.iface.activeLayer()
        if not layer or layer.type() != QgsMapLayer.VectorLayer:
            self._push_message("Warning", "No active vector layer found.", level=1, duration=3)
            return

        if not layer.name().startswith("YOLO Detections"):
            self._push_message("Warning", "Active layer is not a YOLO detection layer.", level=1, duration=3)
            return

        selected_ids = layer.selectedFeatureIds()
        if not selected_ids:
            self._push_message("Info", "No features selected in the active layer.", level=0, duration=2)
            return

        layer_name = layer.name()
        if layer.startEditing():
            if layer.deleteFeatures(selected_ids):
                layer.commitChanges()
                self._push_message("Success", f"Deleted {len(selected_ids)} features from {layer_name}.", level=0, duration=2)
            else:
                layer.rollBack()
                self._push_message("Error", "Failed to delete features.", level=2, duration=4)

    def handle_tiling(self):
        """Splits the current map canvas into multiple image tiles with letterboxing.

        Calculates a grid based on user-defined pixel dimensions. For tiles at 
        the edges that do not fit the full dimensions, the available map area 
        is rendered and padded with a black background (letterboxed).
        """
        p = self.dlg.get_tiling_params()
        if not p["dir"] or not os.path.isdir(p["dir"]):
            self._push_message("Error", "Invalid tiling export path", level=2, duration=4)
            return

        canvas = self.iface.mapCanvas()
        canvas_size = canvas.size()
        t_w, t_h = p["width"], p["height"]
        overlap = p.get("overlap", 0) / 100.0

        step_w = max(1, int(t_w * (1 - overlap)))
        step_h = max(1, int(t_h * (1 - overlap)))

        import math
        cols = max(1, math.ceil((canvas_size.width() - t_w) / step_w) + 1) if canvas_size.width() > t_w else 1
        rows = max(1, math.ceil((canvas_size.height() - t_h) / step_h) + 1) if canvas_size.height() > t_h else 1

        # Render one large image of the map extent matching the tiling span
        preview_size = QSize((cols - 1) * step_w + t_w, (rows - 1) * step_h + t_h)
        settings = QgsMapSettings(canvas.mapSettings())
        settings.setLayers(self._get_filtered_layers())
        base_img = self._render_to_image(settings, preview_size.width(), preview_size.height(), transparent=False)

        # Create a grid image to show tiles separated by a gap
        gap = max(2, int(min(t_w, t_h) * 0.02))
        grid_w = cols * t_w + (cols - 1) * gap
        grid_h = rows * t_h + (rows - 1) * gap
        grid_img = QImage(QSize(grid_w, grid_h), QImage.Format_ARGB32_Premultiplied)
        grid_img.fill(QColor(255, 100, 255))

        painter = QPainter(grid_img)
        for r in range(rows):
            for c in range(cols):
                px_x = c * step_w
                px_y = r * step_h

                # The actual region extracted from the map
                actual_w = min(t_w, preview_size.width() - px_x)
                actual_h = min(t_h, preview_size.height() - px_y)
                tile_rect = QRect(px_x, px_y, actual_w, actual_h)
                tile_sub_img = base_img.copy(tile_rect)

                # Where to draw this tile on the grid
                dest_x = c * (t_w + gap)
                dest_y = r * (t_h + gap)

                # Draw black background padding for the tile
                painter.fillRect(dest_x, dest_y, t_w, t_h, QColor(0, 0, 0))
                # Draw the actual map piece on top
                painter.drawImage(dest_x, dest_y, tile_sub_img)
                
        painter.end()

        pixmap = QPixmap.fromImage(grid_img)
        if pixmap.width() > 800 or pixmap.height() > 600:
            pixmap = pixmap.scaled(800, 600, Qt.KeepAspectRatio, Qt.SmoothTransformation)

        preview = PreviewPopup(pixmap, self.iface.mainWindow())
        preview.setWindowTitle("Tiling Preview")

        buttonBox = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        buttonBox.accepted.connect(preview.accept)
        buttonBox.rejected.connect(preview.reject)
        preview.layout().addWidget(buttonBox)

        if preview.exec_() != QDialog.Accepted:
            return

        # Perform actual tiling
        settings = QgsMapSettings(canvas.mapSettings())
        settings.setLayers(self._get_filtered_layers())

        full_extent = settings.extent()
        canvas_size = settings.outputSize()

        px_w_geo = full_extent.width() / canvas_size.width()
        px_h_geo = full_extent.height() / canvas_size.height()

        total_tiles = cols * rows

        if total_tiles == 0:
            self._push_message("Error", "Tile size is larger than current canvas.", level=2, duration=4)
            return

        count = 0
        for r in range(rows):
            for c in range(cols):
                px_x = c * step_w
                px_y = r * step_h

                actual_w = min(t_w, preview_size.width() - px_x)
                actual_h = min(t_h, preview_size.height() - px_y)

                x_min = full_extent.xMinimum() + (px_x * px_w_geo)
                y_max = full_extent.yMaximum() - (px_y * px_h_geo)
                x_max = x_min + (actual_w * px_w_geo)
                y_min = y_max - (actual_h * px_h_geo)

                tile_extent = QgsRectangle(x_min, y_min, x_max, y_max)
                settings.setExtent(tile_extent)
                settings.setOutputSize(QSize(actual_w, actual_h))

                map_img = self._render_to_image(settings, actual_w, actual_h)

                # Pad to uniform tile size
                final_tile = QImage(QSize(t_w, t_h), QImage.Format_ARGB32_Premultiplied)
                final_tile.fill(QColor(0, 0, 0))

                final_painter = QPainter(final_tile)
                final_painter.drawImage(0, 0, map_img)
                final_painter.end()

                filename = f"tile_{t_w}_{count}.png"
                final_tile.save(os.path.join(p["dir"], filename))

                count += 1

        self._push_message("Success", f"Generated {count} tiles.", level=0, duration=2)

    def handle_preview(self):
        """Reads a YOLO txt file and an image, draws bounding boxes, and shows a popup.

        Args:
            None (Retrieves paths from the UI dialog).
        """
        img_path, txt_path = self.dlg.get_preview_paths()
        if not os.path.exists(img_path) or not os.path.exists(txt_path):
            self._push_message("Error", "Files not found", level=2, duration=4)
            return

        img = QImage(img_path)
        if img.isNull():
            return

        distinct_colors = [
            QColor("red"), QColor("lime"), QColor("blue"), 
            QColor("yellow"), QColor("cyan"), QColor("magenta"), 
            QColor("orange"), QColor("white")
        ]

        w, h = img.width(), img.height()
        painter = QPainter(img)

        with open(txt_path, "r") as f:
            lines = f.readlines()

        for line in lines:
            parts = line.strip().split()
            if len(parts) != 5:
                continue

            class_id = int(parts[0])
            box_color = distinct_colors[class_id % len(distinct_colors)]

            _, xc, yc, bw, bh = map(float, parts)
            x1 = int((xc - bw/2) * w)
            y1 = int((yc - bh/2) * h)
            rect_w = int(bw * w)
            rect_h = int(bh * h)

            pen = QPen(box_color)
            pen.setWidth(3) 
            painter.setPen(pen)
            painter.drawRect(x1, y1, rect_w, rect_h)

        painter.end()

        self.preview_window = PreviewPopup(QPixmap.fromImage(img), parent=self.iface.mainWindow())
        self.preview_window.show()

    def save_layer(self, layer):
        """Persists a memory layer to a shapefile in the project directory.

        If the project has not been saved, prompt the user to save first.

        Args:
            layer (QgsVectorLayer): The memory layer to be saved as a permanent file.
        """
        project_path = QgsProject.instance().fileName()
        if not project_path:
            self._push_message("Warning", "Project not saved. Please save the project to store the YOLO detection layer.", level=1, duration=3)
            return

        project_dir = os.path.dirname(project_path)
        base_name = layer.name().replace(" ", "_").lower()
        shp_path = os.path.join(project_dir, f"{base_name}.shp")

        options = QgsVectorFileWriter.SaveVectorOptions()
        options.driverName = "ESRI Shapefile"
        context = QgsProject.instance().transformContext()

        _, _, new_file, _ = QgsVectorFileWriter.writeAsVectorFormatV3(layer, shp_path, context, options)

        if new_file:
            new_layer = QgsVectorLayer(shp_path, layer.name(), "ogr")
            new_layer.setRenderer(layer.renderer().clone())
            QgsProject.instance().addMapLayer(new_layer)
            QgsProject.instance().removeMapLayer(layer.id())

    def get_or_create_layer(self):
        """Returns an existing target layer or creates a new YOLO Detections memory layer.

        Returns:
            QgsVectorLayer: The layer where detections will be added.
        """
        save_option = self.dlg.get_save_option()
        if save_option == "new":
            existing_numbers = []
            for lyr in QgsProject.instance().mapLayers().values():
                if lyr.name().startswith("YOLO Detections "):
                    try:
                        num = int(lyr.name().split(" ")[-1])
                        existing_numbers.append(num)
                    except ValueError:
                        pass

            next_num = 1 if not existing_numbers else max(existing_numbers) + 1
            layer_name = f"YOLO Detections {next_num}"
            layer = QgsVectorLayer("Polygon?crs=EPSG:3857", layer_name, "memory")

            pr = layer.dataProvider()
            pr.addAttributes([QgsField("class", QMetaType.Type.QString)])
            layer.updateFields()
            QgsProject.instance().addMapLayer(layer)
        else:
            target_name = self.dlg.get_target_layer_name()
            layer = self._get_layer_by_name(target_name)

            if layer is None:
                self._push_message("Error", "Target layer not found, creating new.", level=2, duration=4)
                return self.get_or_create_layer()

            if layer.fields().indexFromName("class") == -1:
                if layer.isEditable() or layer.startEditing():
                    layer.addAttribute(QgsField("class", QMetaType.Type.QString))
                    layer.commitChanges()

        return layer

    def render_layer_to_image(self, layer):
        """Renders a vector layer to an off-screen image using current canvas settings.

        Args:
            layer (QgsMapLayer): The layer to be rendered.

        Returns:
            QImage: The rendered image shaped to the current canvas dimensions.
        """
        canvas = self.iface.mapCanvas()
        settings = QgsMapSettings()
        settings.setExtent(canvas.extent())
        settings.setOutputSize(QSize(canvas.width(), canvas.height()))
        settings.setDestinationCrs(canvas.mapSettings().destinationCrs())
        settings.setLayers([layer])
        return self._render_to_image(settings, canvas.width(), canvas.height())

    def add_detection_feature(self, extent, width, height, box,class_name, features, detected_classes, format="xyxy"):
        if format == "cxcywh":  # ONNX
            cx, cy, w, h = box
            x_min = (cx - w / 2) * width
            y_min = (cy - h / 2) * height
            x_max = (cx + w / 2) * width
            y_max = (cy + h / 2) * height
        else:  # YOLO
            x_min, y_min, x_max, y_max = box
        
        x1 = extent.xMinimum() + (x_min / width) * extent.width()
        y1 = extent.yMaximum() - (y_min / height) * extent.height()
        x2 = extent.xMinimum() + (x_max / width) * extent.width()
        y2 = extent.yMaximum() - (y_max / height) * extent.height()
        detected_classes.add(class_name)

        feat = QgsFeature()
        feat.setGeometry(QgsGeometry.fromPolygonXY([[QgsPointXY(x1,y1), QgsPointXY(x2,y1), QgsPointXY(x2,y2), QgsPointXY(x1,y2), QgsPointXY(x1,y1)]]))
        feat.setAttributes([class_name])
        features.append(feat)

    def detect_objects(self):
        """Runs inference on the rendered image and creates polygon features.

        Supports standard YOLO (.pt/.onnx) and other ONNX models (DFINE, RFDETR).
        Features are added to the target layer and styled based on UI selections.
        """
        img = self.render_layer_to_image(self.selectedLayer)
        width, height = img.width(), img.height()
        ptr = img.bits()
        ptr.setsize(img.byteCount())
        img_array = np.array(ptr).reshape((height, width, 4))
        img_rgb = img_array[..., :3][..., ::-1]  # RGBA to BGR

        extent = self.iface.mapCanvas().extent()
        features = []
        detected_classes = set()

        # Execute selected models
        for m_path in self.models_to_run:
            model = self.get_model(m_path)
            if not model:
                continue

            # YOLO models (Ultralytics)
            if isinstance(model, YOLO):
                results = model.predict(img_rgb)
                for r in results:
                    for i, box in enumerate(r.boxes.xyxy):
                        score = float(r.boxes.conf[i].item())
                        if score < self.conf_threshold:
                            continue

                        raw_name = r.names[int(r.boxes.cls[i].item())]
                        class_name = raw_name.lower()
                        
                        self.add_detection_feature(extent, width, height, box.tolist(), class_name, features, detected_classes, format="xyxy")

            # ONNX models (DFINE, RFDETR)
            elif isinstance(model, InferenceSession):
                input_name = model.get_inputs()[0].name
                input_shape = model.get_inputs()[0].shape
                h_in, w_in = input_shape[2], input_shape[3]

                # Resize and normalize image for model input
                resized = cv2.resize(cv2.cvtColor(img_rgb, cv2.COLOR_BGR2RGB), (w_in, h_in))
                tensor = np.expand_dims(np.transpose(resized.astype(np.float32) / 255.0, (2, 0, 1)), axis=0)

                outputs = model.run(None, {input_name: tensor})
                output_names = [o.name for o in model.get_outputs()]

                if "logits" in output_names:
                    logits, boxes = outputs[output_names.index("logits")], outputs[output_names.index("boxes")]
                else:
                    boxes, logits = outputs[output_names.index("dets")], outputs[output_names.index("labels")]

                logits, boxes = np.squeeze(logits), np.squeeze(boxes)
                scores = np.max(logits, axis=-1)
                labels = np.argmax(logits, axis=-1)

                for box, score, cls in zip(boxes, scores, labels):
                    if score < self.conf_threshold:
                        continue

                    class_name = list(self.object_ids.keys())[int(cls)]
                    self.add_detection_feature(extent, width, height, box.tolist(), class_name, features, detected_classes, format="cxcywh")

            else:
                self._push_message("Error", "Unsupported model type.", level=2, duration=4)
                return

        if not features:
            self._push_message("Info", "No objects detected", level=1, duration=2)
            return

        # Commit features to layer
        layer = self.get_or_create_layer()
        layer.dataProvider().addFeatures(features)
        layer.updateExtents()

        # Apply symbology from UI colors
        fill_alpha = int(255 * (1 - self.dlg.get_fill_transparency() / 100))
        outline_alpha = int(255 * (1 - self.dlg.get_outline_transparency() / 100))
        categories = []
        for name in detected_classes:
            colors = self.class_colors.get(name)

            if colors is None:
                f_c = QColor("white")
                o_c = QColor("black")
            else:
                f_c = QColor(colors.get("fill", "white"))
                o_c = QColor(colors.get("outline", "black"))
            
            sym = QgsFillSymbol.createSimple({
                "outline_width": "1.0",
                "color": f"{f_c.red()},{f_c.green()},{f_c.blue()},{fill_alpha if self.dlg.get_fill_enabled() else 0}",
                "outline_color": f"{o_c.red()},{o_c.green()},{o_c.blue()},{outline_alpha}",
            })
            categories.append(QgsRendererCategory(name, sym, name))

        # Preserve existing categories if appending
        if categories:
            if not self.is_new_mode:
                old_renderer = layer.renderer()
                if isinstance(old_renderer, QgsCategorizedSymbolRenderer):
                    for cat in old_renderer.categories():
                        if cat.value() not in [c.value() for c in categories]:
                            categories.append(cat)

        layer.setRenderer(QgsCategorizedSymbolRenderer("class", categories))
        layer.triggerRepaint()
        self.save_layer(layer)
        self._push_message("Success", f"Detected {len(features)} object(s).", level=0, duration=2)
